9507:
    station_id: 9507
    station_name: "Helenelunds Station"
    distance: 16
    lines:
        36: 2
    traffic_type: "Trains"

3748:
    station_id: 3748
    station_name: "Kista Alléväg"
    distance: 5
    lines:
        627: 2
        514: 1
    traffic_type: "Buses"

50579:
    station_id: 50579
    station_name: "Kista Centrum"
    distance: 10
    lines:
        523: 2
        179: 1
    traffic_type: "Buses"
